name: Deploy

on:
  push:
    branches: [main, develop]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            echo "PULUMI_STACK=demo-azure-webapp-app" >> $GITHUB_ENV
            echo "PULUMI_STACK_PASSPHRASE=${{ secrets.PULUMI_STACK_PASSPHRASE_APP }}" >> $GITHUB_ENV
          else
            echo "PULUMI_STACK=demo-azure-webapp-dev" >> $GITHUB_ENV
            echo "PULUMI_STACK_PASSPHRASE=${{ secrets.PULUMI_STACK_PASSPHRASE_DEV }}" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules from cache
        id: restoreNodeModules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package*.json') }}

      - name: npm ci
        if: steps.restoreNodeModules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Pulumi up
        uses: ./.github/actions/pulumi-up
        with:
          pulumi-azure-storage-account: ${{ secrets.PULUMI_AZURE_STORAGE_ACCOUNT }}
          pulumi-azure-storage-key: ${{ secrets.PULUMI_AZURE_STORAGE_KEY }}
          pulumi-stack: ${{ env.PULUMI_STACK }}
          pulumi-stack-passphrase: ${{ env.PULUMI_STACK_PASSPHRASE }}
