name: Promote to approbation

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Merge Fast-Forward to develop
        run: |
          git fetch origin develop:develop_tmp
          git merge --ff develop_tmp

      - name: Pulumi up
        uses: ./.github/actions/pulumi-up
        with:
          pulumi-azure-storage-account: ${{ secrets.PULUMI_AZURE_STORAGE_ACCOUNT }}
          pulumi-azure-storage-key: ${{ secrets.PULUMI_AZURE_STORAGE_KEY }}
          pulumi-stack: demo-azure-webapp-app
          pulumi-stack-passphrase: ${{ secrets.PULUMI_STACK_PASSPHRASE_APP }}
      
      - name: Push changes
        run: git push origin main